In [1]:
import os
import pandas as pd

In [2]:
path = 'C:\\Users\\Patrik\\Downloads\\webrobots.iokickstarter-datasets\\'
dir_list = os.listdir(path)
dir_list.sort()
dir_list

['Kickstarter_2015-11-01T14_09_04_557Z',
 'Kickstarter_2015-12-17T12_09_06_107Z',
 'Kickstarter_2016-01-28T09_15_08_781Z',
 'Kickstarter_2016-03-22T07_41_08_591Z',
 'Kickstarter_2016-04-15T02_09_04_328Z',
 'Kickstarter_2016-05-15T02_04_46_813Z',
 'Kickstarter_2016-06-15T02_04_49_697Z',
 'Kickstarter_2016-07-15T02_04_40_862Z',
 'Kickstarter_2016-08-15T02_04_03_829Z',
 'Kickstarter_2016-09-15T02_04_03_474Z',
 'Kickstarter_2016-10-15T02_04_11_689Z',
 'Kickstarter_2016-11-12T22_20_03_295Z',
 'Kickstarter_2016-12-15T22_20_52_411Z',
 'Kickstarter_2017-01-15T22_21_04_985Z',
 'Kickstarter_2017-02-15T22_22_48_377Z',
 'Kickstarter_2017-03-15T22_20_55_874Z',
 'Kickstarter_2017-04-15T22_21_18_122Z',
 'Kickstarter_2017-05-15T22_21_11_300Z',
 'Kickstarter_2017-06-15T22_20_03_059Z',
 'Kickstarter_2017-07-15T22_20_48_951Z',
 'Kickstarter_2017-08-15T22_20_51_958Z',
 'Kickstarter_2017-09-15T22_20_48_432Z']

In [3]:
len(dir_list)

22

In [4]:
cols_to_keep_end_state = ['id','pledged','state','disable_communication','state_changed_at',
                          'backers_count','static_usd_rate','usd_pledged','spotlight']

In [5]:
cols_to_drop_end_state = ['name',
                          'blurb',
                          'goal',
                          'slug',
                          'country',
                          'currency',
                          'currency_symbol',
                          'currency_trailing_code',
                          'deadline',
                          'state_changed_at',
                          'created_at',
                          'launched_at',
                          'static_usd_rate',
                          'photo',
                          'creator',
                          'location',
                          'category',
                          'profile',
                          'urls',
                          'source_url']

In [6]:
df_live = pd.DataFrame()
df_live_after_end = pd.DataFrame()
csv_count = 0

In [7]:
# for each directory containing csv files
for dir in dir_list:
    print('\n>>> DIRECTORY: '+dir)
    csv_list = os.listdir(path+dir)
    csv_count += len(csv_list)
    for csv in csv_list:
        print(csv, end=', ')
        data = pd.read_csv(path+dir+'\\'+csv)
        # fetch data about live projects
        df_live = df_live.append(data[data['state']=='live'], ignore_index=True)
        
        # drop selected columns
        data.drop(cols_to_drop_end_state, axis=1, inplace=True)
        
        # fetch data about projects marked 'live' in previous periods after their end in following periods
        df_live_after_end = df_live_after_end.append(data[data['state']!='live'], ignore_index=True)
        df_live_after_end = df_live_after_end[df_live_after_end['id'].isin(df_live['id'])]
        
        # we only need the first state after the end of a project
        # so remove all rows that capture chronologically later state of a project
        df_live_after_end.drop_duplicates(subset='id', inplace=True)
        
print('\n\nTotal: ' + str(csv_count) + ' csv files in ' + str(len(dir_list)) + ' directories')

>>> DIRECTORY: Kickstarter_2015-11-01T14_09_04_557Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv,
>>> DIRECTORY: Kickstarter_2015-12-17T12_09_06_107Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv,
>>> DIRECTORY: Kickstarter_2016-01-28T09_15_08_781Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv,
>>> DIRECTORY: Kickstarter_2016-03-22T07_41_08_591Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv,
>>> DIRECTORY: Kickstarter_2016-04-15T02_09_04_328Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv,
>>> DIRECTORY: Kickstarter_2016-05-15T02_04_46_813Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv,
>>> DIRECTORY: Kickstarter_2016-06-15T02_04_49_697Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv,
>>> DIRECTORY: Kickstarter_2016-07-15T02_04_40_862Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv,
>>> DIRECTORY: Kickstarter_2016-08-15T02_04_03_829Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv,
>>> DIRECTORY: Kickstarter_2016-09-15T02_04_03_474Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv,
>>> DIRECTORY: Kickstarter_2016-10-15T02_04_11_689Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv,
>>> DIRECTORY: Kickstarter_2016-11-12T22_20_03_295Z

Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv,
>>> DIRECTORY: Kickstarter_2016-12-15T22_20_52_411Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv, Kickstarter041.csv,
>>> DIRECTORY: Kickstarter_2017-01-15T22_21_04_985Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv, Kickstarter041.csv,
>>> DIRECTORY: Kickstarter_2017-02-15T22_22_48_377Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv, Kickstarter041.csv, Kickstarter042.csv,
>>> DIRECTORY: Kickstarter_2017-03-15T22_20_55_874Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv, Kickstarter041.csv, Kickstarter042.csv, Kickstarter043.csv,
>>> DIRECTORY: Kickstarter_2017-04-15T22_21_18_122Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv, Kickstarter041.csv, Kickstarter042.csv, Kickstarter043.csv,
>>> DIRECTORY: Kickstarter_2017-05-15T22_21_11_300Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv, Kickstarter041.csv, Kickstarter042.csv, Kickstarter043.csv, Kickstarter044.csv,
>>> DIRECTORY: Kickstarter_2017-06-15T22_20_03_059Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv, Kickstarter041.csv, Kickstarter042.csv, Kickstarter043.csv, Kickstarter044.csv, Kickstarter045.csv, Kickstarter046.csv, Kickstarter047.csv,
>>> DIRECTORY: Kickstarter_2017-07-15T22_20_48_951Z

Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv, Kickstarter041.csv, Kickstarter042.csv, Kickstarter043.csv, Kickstarter044.csv, Kickstarter045.csv, Kickstarter046.csv, Kickstarter047.csv,
>>> DIRECTORY: Kickstarter_2017-08-15T22_20_51_958Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv, Kickstarter039.csv, Kickstarter040.csv, Kickstarter041.csv,
>>> DIRECTORY: Kickstarter_2017-09-15T22_20_48_432Z
Kickstarter.csv, Kickstarter001.csv, Kickstarter002.csv, Kickstarter003.csv, Kickstarter004.csv, Kickstarter005.csv, Kickstarter006.csv, Kickstarter007.csv, Kickstarter008.csv, Kickstarter009.csv, Kickstarter010.csv, Kickstarter011.csv, Kickstarter012.csv, Kickstarter013.csv, Kickstarter014.csv, Kickstarter015.csv, Kickstarter016.csv, Kickstarter017.csv, Kickstarter018.csv, Kickstarter019.csv, Kickstarter020.csv, Kickstarter021.csv, Kickstarter022.csv, Kickstarter023.csv, Kickstarter024.csv, Kickstarter025.csv, Kickstarter026.csv, Kickstarter027.csv, Kickstarter028.csv, Kickstarter029.csv, Kickstarter030.csv, Kickstarter031.csv, Kickstarter032.csv, Kickstarter033.csv, Kickstarter034.csv, Kickstarter035.csv, Kickstarter036.csv, Kickstarter037.csv, Kickstarter038.csv,

Total: 856 csv files in 22 directories

In [8]:
df_live[df_live['id'].isin(df_live_after_end['id'])].describe()

,backers_count,created_at,deadline,goal,id,last_update_published_at,launched_at,pledged,state_changed_at,static_usd_rate,unread_messages_count,unseen_activity_count,usd_pledged
count,63337.000000,6.333700e+04,6.333700e+04,6.333700e+04,6.333700e+04,1.000000e+00,6.333700e+04,6.333700e+04,6.333700e+04,63337.000000,1.0,1.0,6.333700e+04
mean,93.765524,1.467000e+09,1.474815e+09,6.790204e+04,1.073324e+09,1.478839e+09,1.471638e+09,9.701196e+03,1.471638e+09,0.995013,9.0,0.0,8.563591e+03
std,935.594847,2.030087e+07,1.614159e+07,1.383193e+06,6.194101e+08,NaN,1.618776e+07,8.809588e+04,1.618776e+07,0.219489,NaN,NaN,8.375733e+04
min,0.000000,1.266343e+09,1.446392e+09,1.000000e+00,1.852000e+04,1.478839e+09,1.441143e+09,0.000000e+00,1.441143e+09,0.045635,9.0,0.0,0.000000e+00
25%,1.000000,1.454944e+09,1.461860e+09,2.500000e+03,5.375727e+08,1.478839e+09,1.458575e+09,1.100000e+01,1.458575e+09,1.000000,9.0,0.0,1.118898e+01
50%,7.000000,1.467147e+09,1.474232e+09,7.000000e+03,1.072535e+09,1.478839e+09,1.470914e+09,3.813700e+02,1.470914e+09,1.000000,9.0,0.0,3.659016e+02
75%,41.000000,1.482715e+09,1.488733e+09,2.000000e+04,1.606598e+09,1.478839e+09,1.485792e+09,2.960000e+03,1.485792e+09,1.000000,9.0,0.0,2.772000e+03
max,145232.000000,1.502821e+09,1.507937e+09,1.000000e+08,2.147422e+09,1.478839e+09,1.502840e+09,1.102400e+07,1.502840e+09,1.557361,9.0,0.0,1.102400e+07

In [9]:
df_live.drop_duplicates(subset='id', inplace=True)
df_live[df_live['id'].isin(df_live_after_end['id'])].describe()

,backers_count,created_at,deadline,goal,id,last_update_published_at,launched_at,pledged,state_changed_at,static_usd_rate,unread_messages_count,unseen_activity_count,usd_pledged
count,55410.000000,5.541000e+04,5.541000e+04,5.541000e+04,5.541000e+04,1.000000e+00,5.541000e+04,5.541000e+04,5.541000e+04,55410.000000,1.0,1.0,5.541000e+04
mean,88.107598,1.466783e+09,1.474412e+09,5.641756e+04,1.072683e+09,1.478839e+09,1.471422e+09,9.033351e+03,1.471422e+09,0.996482,9.0,0.0,7.937948e+03
std,751.474603,2.048272e+07,1.634067e+07,1.185082e+06,6.196330e+08,NaN,1.642256e+07,8.390334e+04,1.642256e+07,0.217971,NaN,NaN,7.975358e+04
min,0.000000,1.266343e+09,1.446392e+09,1.000000e+00,1.852000e+04,1.478839e+09,1.441143e+09,0.000000e+00,1.441143e+09,0.045635,9.0,0.0,0.000000e+00
25%,1.000000,1.453842e+09,1.461245e+09,2.184000e+03,5.357600e+08,1.478839e+09,1.458217e+09,1.500000e+01,1.458217e+09,1.000000,9.0,0.0,1.341683e+01
50%,8.000000,1.466995e+09,1.473734e+09,7.000000e+03,1.072248e+09,1.478839e+09,1.470758e+09,4.020000e+02,1.470758e+09,1.000000,9.0,0.0,3.850000e+02
75%,41.000000,1.482517e+09,1.488474e+09,2.000000e+04,1.606908e+09,1.478839e+09,1.485658e+09,2.940000e+03,1.485658e+09,1.000000,9.0,0.0,2.775000e+03
max,102203.000000,1.502821e+09,1.507937e+09,1.000000e+08,2.147422e+09,1.478839e+09,1.502840e+09,1.102400e+07,1.502840e+09,1.557361,9.0,0.0,1.102400e+07

In [10]:
df_live_after_end.describe()

,backers_count,id,last_update_published_at,pledged,unread_messages_count,unseen_activity_count,usd_pledged
count,55410.000000,5.541000e+04,0.0,5.541000e+04,0.0,0.0,5.541000e+04
mean,159.653943,1.072683e+09,NaN,1.685332e+04,NaN,NaN,1.483412e+04
std,1167.791434,6.196330e+08,NaN,1.346606e+05,NaN,NaN,1.255857e+05
min,0.000000,1.852000e+04,NaN,0.000000e+00,NaN,NaN,0.000000e+00
25%,2.000000,5.357600e+08,NaN,3.500000e+01,NaN,NaN,3.500000e+01
50%,15.000000,1.072248e+09,NaN,8.340000e+02,NaN,NaN,8.000000e+02
75%,78.000000,1.606908e+09,NaN,6.095000e+03,NaN,NaN,5.765000e+03
max,154926.000000,2.147422e+09,NaN,1.277984e+07,NaN,NaN,1.277984e+07

In [11]:
df_live_after_end

,backers_count,disable_communication,friends,id,is_backing,is_starrable,is_starred,last_update_published_at,permissions,pledged,spotlight,staff_pick,state,unread_messages_count,unseen_activity_count,usd_pledged
0,8,False,NaN,1460620306,NaN,NaN,NaN,NaN,NaN,345.00,False,NaN,failed,NaN,NaN,345.000000
1,0,False,NaN,2144513159,NaN,NaN,NaN,NaN,NaN,0.00,False,NaN,failed,NaN,NaN,0.000000
2,63,False,NaN,2134755894,NaN,NaN,NaN,NaN,NaN,4370.00,True,NaN,successful,NaN,NaN,4370.000000
3,819,False,NaN,989204114,NaN,NaN,NaN,NaN,NaN,102410.00,True,NaN,successful,NaN,NaN,102410.000000
4,65,False,NaN,1545034574,NaN,NaN,NaN,NaN,NaN,10880.77,True,NaN,successful,NaN,NaN,10880.770000
5,42,False,NaN,1553241526,NaN,NaN,NaN,NaN,NaN,7614.00,False,NaN,canceled,NaN,NaN,8582.355753
6,5,False,NaN,1185810012,NaN,NaN,NaN,NaN,NaN,180.00,False,NaN,failed,NaN,NaN,180.000000
7,5,False,NaN,1495670782,NaN,NaN,NaN,NaN,NaN,326.00,False,NaN,failed,NaN,NaN,326.000000
8,1,False,NaN,1173651527,NaN,NaN,NaN,NaN,NaN,1.00,False,NaN,failed,NaN,NaN,0.772431
9,1,False,NaN,1366181168,NaN,NaN,NaN,NaN,NaN,25.00,False,NaN,failed,NaN,NaN,25.000000
10,0,False,NaN,803587677,NaN,NaN,NaN,NaN,NaN,0.00,False,NaN,failed,NaN,NaN,0.000000
11,4,False,NaN,2118436986,NaN,NaN,NaN,NaN,NaN,91.00,False,NaN,failed,NaN,NaN,64.155937
12,0,False,NaN,1975079137,NaN,NaN,NaN,NaN,NaN,0.00,False,NaN,failed,NaN,NaN,0.000000
13,1,False,NaN,118771907,NaN,NaN,NaN,NaN,NaN,12.00,False,NaN,failed,NaN,NaN,12.000000
14,15,False,NaN,424958500,NaN,NaN,NaN,NaN,NaN,900.00,True,NaN,successful,NaN,NaN,900.000000
15,2,False,NaN,1484189351,NaN,NaN,NaN,NaN,NaN,57.00,True,NaN,successful,NaN,NaN,57.000000
16,82,False,NaN,2007656956,NaN,NaN,NaN,NaN,NaN,10061.00,True,NaN,successful,NaN,NaN,11418.149921
17,2,False,NaN,1746816767,NaN,NaN,NaN,NaN,NaN,25.00,False,NaN,canceled,NaN,NaN,25.000000
18,3,False,NaN,1305725229,NaN,NaN,NaN,NaN,NaN,31.00,False,NaN,canceled,NaN,NaN,23.340561
19,4,False,NaN,1826572103,NaN,NaN,NaN,NaN,NaN,200.00,False,NaN,failed,NaN,NaN,200.000000
20,1,False,NaN,394360029,NaN,NaN,NaN,NaN,NaN,100.00,False,NaN,failed,NaN,NaN,100.000000
21,0,False,NaN,1169956436,NaN,NaN,NaN,NaN,NaN,0.00,False,NaN,failed,NaN,NaN,0.000000
22,5,False,NaN,1677647038,NaN,NaN,NaN,NaN,NaN,455.00,False,NaN,failed,NaN,NaN,455.000000
23,4,False,NaN,378145709,NaN,NaN,NaN,NaN,NaN,91.00,False,NaN,failed,NaN,NaN,103.485883
24,2,False,NaN,1198076498,NaN,NaN,NaN,NaN,NaN,16.00,False,NaN,failed,NaN,NaN,16.000000
25,2,False,NaN,1991851255,NaN,NaN,NaN,NaN,NaN,6.00,False,NaN,failed,NaN,NaN,6.000000
26,2,False,NaN,850464716,NaN,NaN,NaN,NaN,NaN,45.00,False,NaN,failed,NaN,NaN,69.639176
27,10,False,NaN,342013412,NaN,NaN,NaN,NaN,NaN,560.00,False,NaN,failed,NaN,NaN,417.289807
28,167,False,NaN,1731207260,NaN,NaN,NaN,NaN,NaN,10412.00,False,NaN,failed,NaN,NaN,10412.000000
29,14,False,NaN,2020737822,NaN,NaN,NaN,NaN,NaN,299.00,False,NaN,failed,NaN,NaN,299.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55380,32,False,NaN,130905606,NaN,False,NaN,NaN,NaN,3222.00,True,False,successful,NaN,NaN,3222.000000
55381,2,False,NaN,1853648874,NaN,False,NaN,NaN,NaN,31.00,False,False,failed,NaN,NaN,31.000000
55382,3,False,NaN,1945296403,NaN,False,NaN,NaN,NaN,135.00,False,False,failed,NaN,NaN,135.000000
55383,1,False,NaN,1619920400,NaN,False,NaN,NaN,NaN,1.00,False,False,failed,NaN,NaN,1.307947
55384,0,False,NaN,1687985695,NaN,False,NaN,NaN,NaN,0.00,False,False,failed,NaN,NaN,0.000000
55385,44,False,NaN,1332802029,NaN,False,NaN,NaN,NaN,1055.00,True,False,successful,NaN,NaN,1355.899968
55386,42,False,NaN,750352191,NaN,False,NaN,NaN,NaN,1575.00,True,False,successful,NaN,NaN,1575.000000
55387,26,False,NaN,1711440926,NaN,False,NaN,NaN,NaN,18200.00,False,False,canceled,NaN,NaN,1036.259042
55388,27,False,NaN,470774753,NaN,False,NaN,NaN,NaN,1594.77,False,False,failed,NaN,NaN,2078.252609
55389,24,False,NaN,1376195021,NaN,False,NaN,NaN,NaN,1740.00,True,False,successful,NaN,NaN,1740.000000
55390,117,False,NaN,602498880,NaN,False,NaN,NaN,NaN,5398.00,True,False,successful,NaN,NaN,5398.000000
55391,27,False,NaN,461542936,NaN,False,NaN,NaN,NaN,3205.00,True,False,successful,NaN,NaN,3205.000000
55392,9,False,NaN,275841217,NaN,False,NaN,NaN,NaN,460.00,False,False,failed,NaN,NaN,364.499924
55393,1,False,NaN,1471396992,NaN,False,NaN,NaN,NaN,1.00,False,False,failed,NaN,NaN,1.000000
55394,61,False,NaN,714374402,NaN,False,NaN,NaN,NaN,87800.00,True,False,successful,NaN,NaN,4854.657794
55395,0,False,NaN,111650021,NaN,False,NaN,NaN,NaN,0.00,False,False,failed,NaN,NaN,0.000000
55396,3,False,NaN,677859791,NaN,False,NaN,NaN,NaN,102.00,False,False,failed,NaN,NaN,102.000000
55397,82,False,NaN,1322033786,NaN,False,NaN,NaN,NaN,10579.00,True,False,successful,NaN,NaN,10579.000000
55398,271,False,NaN,769973046,NaN,False,NaN,NaN,NaN,13028.00,True,True,successful,NaN,NaN,16965.640304
55399,58,False,NaN,2094747709,NaN,False,NaN,NaN,NaN,5050.00,True,False,successful,NaN,NaN,5050.000000
55400,94,False,NaN,643371088,NaN,False,NaN,NaN,NaN,8135.00,True,False,successful,NaN,NaN,10621.380098
55401,91,False,NaN,243579605,NaN,False,NaN,NaN,NaN,15160.00,True,False,successful,NaN,NaN,15160.000000
55523,0,False,NaN,1426253146,NaN,False,NaN,NaN,NaN,0.00,False,False,canceled,NaN,NaN,0.000000
55588,0,False,NaN,249659262,NaN,False,NaN,NaN,NaN,0.00,False,False,failed,NaN,NaN,0.000000
55590,0,False,NaN,1664006774,NaN,False,NaN,NaN,NaN,0.00,False,False,failed,NaN,NaN,0.000000
55591,16,False,NaN,1163430217,NaN,False,NaN,NaN,NaN,776.00,False,False,failed,NaN,NaN,776.000000
55592,10,False,NaN,120323037,NaN,False,NaN,NaN,NaN,740.00,False,False,failed,NaN,NaN,740.000000
56551,72,False,NaN,36092936,NaN,False,NaN,NaN,NaN,33035.00,False,False,canceled,NaN,NaN,1808.357042
56556,30,False,NaN,1176283868,NaN,False,NaN,NaN,NaN,1022.00,False,False,failed,NaN,NaN,1305.771586
56557,18,False,NaN,170692243,NaN,False,NaN,NaN,NaN,2561.00,False,False,failed,NaN,NaN,2561.000000

In [12]:
df_live.to_csv('live.csv')

In [13]:
df_live_after_end.to_csv('ended.csv')

In [14]:
x = pd.read_csv('ended.csv')

C:\Users\Patrik\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (6,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [15]:
y = pd.read_csv('live.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 20: invalid continuation byte

In [ ]:
# df_live = pd.read_csv('live.csv', index_col=0, encoding='cp1252')
# df_live_after_end.columns = [str(col)+'_end' for col in df_live_after_end.columns]